### ISSUE TITLE
Add meta block

### ISSUE THREAD

**Issue by rsmith013** [cedadev/fwtheme-django#18]
Add Jinja block to make it easy to add in additional HTML meta tags

**Comment by amanning9** [comment]
On the bootstrap5 branch, I think this is fixed in https://github.com/cedadev/fwtheme-django/commit/44e0cd8e747f7d9a47f3ee1d748115f590782e06

**Comment by rsmith013** [comment]
ok, I have merged it now but made it explicitly for meta tags. {% block extra_meta %}
Also means that it will appear at the top of the HTML. The extra head bit is fine to stay but should probably be for other things.
